---
- name: Execute command on host
  hosts: all
  tasks:
    - name: Command to list files
      ansible.builtin.shell: ls -la | grep README.md
      register: my_output

    - name: Display my_output
      ansible.builtin.debug:
        msg: "my_output looks like: {{ my_output.stdout }}"
