---
- name: Install nginx using awx and Ansible
  hosts: all
  become: yes
  tasks:
    - name: Install nginx
      apt:
        name: nginx
        state: present

    - name: Start the nginx service
      service:
        name: nginx
        state: started
