---
- name: Provision Storage Account in Azure Cloud
  hosts: localhost
  gather_facts: no

  tasks:
    - name: Create storage account
      azure.azcollection.azure_rm_storageaccount:
        resource_group: "{{ resource_group_name }}"
        name: "{{ storage_account_name }}"
        account_type: Standard_LRS
