---
- name: Playbook to create GCS Bucket
  hosts: localhost
  gather_facts: no

  tasks:
    - name: create a disk
      google.cloud.gcp_compute_disk:
        name: disk-instance
        size_gb: 50
        source_image: projects/debian-cloud/global/images/family/debian-11
        zone: us-central1-a
        project: "{{ gcp_project }}"
        auth_kind: serviceaccount
        state: present
      register: disk

    - name: create a instance
      google.cloud.gcp_compute_instance:
        name: "{{ gcp_vm_name }}"
        machine_type: n1-standard-1
        disks:
        - auto_delete: 'true'
          boot: 'true'
          source: "{{ disk }}"
        - auto_delete: 'true'
          interface: NVME
          type: SCRATCH
          initialize_params:
            disk_type: local-ssd
        metadata:
          cost-center: '12345'
        labels:
          environment: testing
        network_interfaces:
        - network:
            name: default
          access_configs:
          - name: External NAT
            type: ONE_TO_ONE_NAT
        zone: us-central1-a
        project: "{{ gcp_project }}"
        auth_kind: serviceaccount
        state: present
